"""Item timestamp

Revision ID: 0f8148d3a44c
Revises: 19d88ab7b1c2
Create Date: 2024-12-01 19:59:36.920135

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0f8148d3a44c'
down_revision: Union[str, None] = '19d88ab7b1c2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('item', sa.Column('timestamp', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('item', 'timestamp')
    # ### end Alembic commands ###
