"""Feedback timestamp

Revision ID: 19d88ab7b1c2
Revises: 81e24e2f477b
Create Date: 2024-12-01 19:57:32.623224

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '19d88ab7b1c2'
down_revision: Union[str, None] = '81e24e2f477b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('feedback', sa.Column('timestamp', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('feedback', 'timestamp')
    # ### end Alembic commands ###
